//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCFTPOracle.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.3.81;Initial Catalog=EnvioFTPOracle;Persist Security Info=True" +
            ";User ID=envio_ftp;Password=Apl1c4t1v0")]
        public string EnvioFTPOracleConnectionString {
            get {
                return ((string)(this["EnvioFTPOracleConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.14.68;Initial Catalog=Ftp;Persist Security Info=True;User ID=a" +
            "dminDBA;Password=\"U=8vwq%@btP4_VBM\"")]
        public string FtpConnectionString {
            get {
                return ((string)(this["FtpConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.14.68;Initial Catalog=Ftp;Persist Security Info=True;User ID=a" +
            "dminDBA;Password=U=8vwq%@btP4_VBM")]
        public string EnvioFTPOracleConnectionString1 {
            get {
                return ((string)(this["EnvioFTPOracleConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.11.31;Initial Catalog=EnvioFTPOracle;Persist Security Info=Tr" +
            "ue;User ID=envio_ftp;Password=Apl1c4t1v0")]
        public string EnvioFTPOracleConnectionString2 {
            get {
                return ((string)(this["EnvioFTPOracleConnectionString2"]));
            }
        }
    }
}
